# SPDX-FileCopyrightText: 2025 Henrik Jakob jakob@ibb.uni-stuttgart.de
# SPDX-License-Identifier: GPL-3.0-or-later

style = "sciml"
margin = 108
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true