# SPDX-FileCopyrightText: 2025 Henrik Jakob jakob@ibb.uni-stuttgart.de
# SPDX-License-Identifier: MIT

name: Check build
on:
  push:
    paths-ignore:
      - "**/*.md"

  pull_request:
    types: [opened]
    branches:
      - main
  workflow_dispatch:
  
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "ubuntu-gcc",
              container: "henrij22/ubuntu-julia-muesli:latest",
            }
    container:
      image: ${{ matrix.config.container }}
      options: --memory-swap="20g" --memory="20g" --cpus="2" --user root
    steps:
      - uses: actions/checkout@v4
        with:
          path: "repo"

      - name: Build
        working-directory: ./repo
        run: |
          # Create and navigate to the build directory
          mkdir cmake-build-${{ matrix.config.name }}
          cd cmake-build-${{ matrix.config.name }}
          
          # Read the contents of temp/prefix
          if [ -f /tmp/prefix.txt ]; then
            PREFIX_PATH=$(tr -d '\n' < /tmp/prefix.txt)
            echo "CMAKE_PREFIX_PATH set to: '$PREFIX_PATH'"

          else
            echo "/tmp/prefix.txt file not found!"
            exit 1
          fi
          
          # Run CMake with the specified prefix path
          cmake -DCMAKE_PREFIX_PATH="$PREFIX_PATH" ../
          
          # Build the target
          cmake --build . --parallel 2 --target jlmuesli
